version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: bank-account-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=BankAccountDb
    volumes:
      - mongodb_data:/data/db
    networks:
      - bank-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: bank-account-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - bank-network
    depends_on:
      - mongodb
    restart: unless-stopped

networks:
  bank-network:
    driver: bridge

volumes:
  mongodb_data: